<a href="https://colab.research.google.com/github/Nikibort/data_303_project/blob/main/data_303_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install folium
!pip install geopandas

Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2026.2.25)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [ ]:
import pandas as pd
import folium
import geopandas as gpd

In [ ]:
data = pd.read_csv('tx_san_antonio_2023_01_26.csv', low_memory = False)
data.head()
#data.shape

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,vehicle_make,vehicle_model,vehicle_registration_state,vehicle_year,raw_race,raw_posted_speed,raw_actual_speed,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made
0,1310907,2018-01-12,12:55:00,9238 N LOOP 1604 W,29.553710,-98.663222,GM,7350.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
1,1362032,2018-04-25,01:30:00,263 NELOOP 410,29.737933,-99.083636,SU,NaN,NaN,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
2,1360759,2018-04-20,23:47:00,6802 UTSA ...,29.576257,-98.622383,GM,7250.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
3,1373277,2018-05-16,21:00:00,4718 ALLEGHENY ...,29.494494,-98.578381,SU,7140.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
4,1395612,2018-06-27,00:00:00,8501 BROADWAY,29.517618,-98.464292,GM,3360.0,NORTH,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN

In [ ]:
data.dropna(subset=['raw_row_number', 'date', 'time', 'location', 'lat', 'lng'], inplace=True)
data.head()
data.shape

(629676, 33)

In [ ]:
data = data.drop(columns = ['vehicle_make',	'vehicle_model', 'vehicle_registration_state'])

In [ ]:
data

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,speed,posted_speed,vehicle_color,vehicle_year,raw_race,raw_posted_speed,raw_actual_speed,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made
0,1310907,2018-01-12,12:55:00,9238 N LOOP 1604 W,29.553710,-98.663222,GM,7350.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
1,1362032,2018-04-25,01:30:00,263 NELOOP 410,29.737933,-99.083636,SU,NaN,NaN,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
2,1360759,2018-04-20,23:47:00,6802 UTSA ...,29.576257,-98.622383,GM,7250.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
3,1373277,2018-05-16,21:00:00,4718 ALLEGHENY ...,29.494494,-98.578381,SU,7140.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
4,1395612,2018-06-27,00:00:00,8501 BROADWAY,29.517618,-98.464292,GM,3360.0,NORTH,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301098,1480597,2018-12-12,00:00:00,FRIO,29.420158,-98.504575,GM,2160.0,CENTRAL,61.0,...,NaN,NaN,NaN,NaN,H,-,-,NaN,NaN,NaN
1301099,1480601,2018-12-12,00:00:00,FRIO,29.420158,-98.504575,GM,2160.0,CENTRAL,61.0,...,NaN,NaN,NaN,NaN,H,-,-,NaN,NaN,NaN
1301100,1480600,2018-12-12,00:00:00,FRIO,29.420158,-98.504575,GM,2160.0,CENTRAL,61.0,...,NaN,NaN,NaN,NaN,H,-,-,NaN,NaN,NaN
1301101,1480598,2018-12-12,00:00:00,FRIO,29.420158,-98.504575,GM,2160.0,CENTRAL,61.0,...,NaN,NaN,NaN,NaN,H,-,-,NaN,NaN,NaN
1301102,1572423,2019-07-18,06:34:00,0,29.518704,-98.507800,GM,NaN,NaN,31.0,...,NaN,NaN,OTHER,2011.0,U,-,-,NaN,NaN,NaN