In [1]:
import plotly.express as px
import pandas as pd

In [2]:
df = pd.read_csv('san_antonio.csv', low_memory = False)
df.head()

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,vehicle_make,vehicle_model,vehicle_registration_state,vehicle_year,raw_race,raw_posted_speed,raw_actual_speed,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made
0,1310907,2018-01-12,12:55:00,9238 N LOOP 1604 W,29.553710,-98.663222,GM,7350.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
1,1362032,2018-04-25,01:30:00,263 NELOOP 410,29.737933,-99.083636,SU,NaN,NaN,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
2,1360759,2018-04-20,23:47:00,6802 UTSA ...,29.576257,-98.622383,GM,7250.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
3,1373277,2018-05-16,21:00:00,4718 ALLEGHENY ...,29.494494,-98.578381,SU,7140.0,PRUE,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN
4,1395612,2018-06-27,00:00:00,8501 BROADWAY,29.517618,-98.464292,GM,3360.0,NORTH,18.0,...,NaN,NaN,NaN,NaN,U,-,-,NaN,NaN,NaN

In [3]:
df.shape

(1301103, 33)

In [4]:
#dropping raws with NaN in important columns
df.dropna(subset=['raw_custodial_arrest_made','raw_row_number', 'date', 'time', 'type'], inplace=True)
df.shape

(187891, 33)

In [5]:
# Splitting date column
df['date'] = pd.to_datetime(df['date'])
df['month_year'] = df['date'].dt.to_period('M').astype(str)
df.head()

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,vehicle_model,vehicle_registration_state,vehicle_year,raw_race,raw_posted_speed,raw_actual_speed,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made,month_year
116,796684|796685,2015-04-03,20:35:00,31 RUE CHARLES,29.517630,-98.434382,GM,3360.0,NORTH,24.0,...,PDF,TX,2014.0,W,-,-,No Search,No,No,2015-04
260,115,2012-01-01,21:21:00,NWLOOP 410,29.488975,-98.567335,GM,5260.0,WEST,20.0,...,PDF,TX,2011.0,H,-,-,No Search,No,No,2012-01
1842,1699,2012-01-05,15:31:00,5000 DE ZAVALA ...,29.567590,-98.579971,GM,7230.0,PRUE,17.0,...,TACO,TX,1996.0,W,--,--,No Search,No,No,2012-01
1843,1700,2012-01-05,15:31:00,5000 DE ZAVALA ...,29.567590,-98.579971,GM,7230.0,PRUE,17.0,...,TACO,TX,1996.0,W,-,-,No Search,No,No,2012-01
2195,2052|2053,2012-01-31,23:28:00,1600 WILSON ...,29.462010,-98.540728,GM,5210.0,WEST,19.0,...,MALI,TX,2009.0,H,--|-,--|-,No Search,No,No,2012-01

In [6]:
df = df.sort_values(by='month_year', ascending=True)
df

,raw_row_number,date,time,location,lat,lng,geocode_source,district,substation,subject_age,...,vehicle_model,vehicle_registration_state,vehicle_year,raw_race,raw_posted_speed,raw_actual_speed,raw_search_reason,raw_contraband_or_evidence,raw_custodial_arrest_made,month_year
357205,68533|68534|68535,2012-01-30,12:09:00,2400 RIGSBY,29.399359,-98.421436,GM,4230.0,EAST,30.0,...,PDF,TX,2004.0,B,--|-|-,--|-|-,No Search,No,No,2012-01
344246,51015,2012-01-13,15:10:00,3200 E IH 10,29.413354,-98.432242,GM,4160.0,EAST,52.0,...,ACC,TX,2011.0,W,--,--,No Search,No,No,2012-01
344238,51001,2012-01-20,03:36:00,2800 E SOUTHCROSS ...,29.376420,-98.449561,GM,4220.0,EAST,41.0,...,F150,TX,2000.0,H,-,-,No Search,No,No,2012-01
344237,51000,2012-01-16,18:41:00,SUN CANYON ...,29.465931,-98.373441,GM,4320.0,EAST,76.0,...,ASTV,TX,2000.0,H,-,-,No Search,No,No,2012-01
344236,50998|50999,2012-01-10,18:23:00,MYSTIC SUNRISE,29.466004,-98.368789,GM,4320.0,EAST,57.0,...,ACCE,TX,2008.0,H,-,-,No Search,No,No,2012-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325689,1684156,2020-06-02,14:00:00,6000 NW LOOP 410,29.475454,-98.609479,SU,5270.0,WEST,19.0,...,99,TX,2014.0,H,--,--,No Search,No,No,2020-06
325690,1684179|1684180,2020-06-02,14:45:00,6000 NWLOOP 410,NaN,NaN,NaN,NaN,NaN,26.0,...,99,TX,2017.0,H,-|--,-|--,No Search,No,No,2020-06
325691,1686492,2020-06-15,10:50:00,3900 NWLOOP 410,29.490830,-98.558845,GM,5260.0,WEST,31.0,...,NaN,NaN,NaN,W,-,-,No Search,No,No,2020-06
325646,1685102,2020-06-09,01:30:00,700 E EUCLID ...,29.440560,-98.488412,SU,2140.0,CENTRAL,26.0,...,PDF,TX,2000.0,H,-,-,No Search,No,No,2020-06
322489,1686082|1686083,2020-06-13,08:14:00,2500 LAREDO,29.412711,-98.523135,SU,2340.0,CENTRAL,29.0,...,PDF,TX,2013.0,W,-,-,No Search,No,No,2020-06

In [7]:
graph_df = df.groupby('month_year').size().reset_index(name='stop_count')
graph_df.head()

  month_year  stop_count
0    2012-01        2990
1    2012-02        2807
2    2012-03        2464
3    2012-04        2364
4    2012-05        2705

In [8]:
fig = px.line(graph_df, x='month_year', y='stop_count', 
              title='Monthly Police Stops in San Antonio (Jan. 2012 - Mar. 2020)',
              labels={'month_year': 'Month', 'stop_count': 'Total Stops That Month'})
fig.show()